import React, { useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link, NavLink, useNavigate, useLocation } from 'react-router-dom';
import { Hand, Home as HomeIcon, BookOpen, BarChart3, UserRound, ChevronRight, Play, Camera, Check, Sparkles, ArrowLeft, RotateCcw, PenLine, LockKeyhole, Menu, X, Video, Image as ImageIcon, CircleHelp } from 'lucide-react';
import './styles.css';

const cats = [
  { name:'คำทักทาย', icon:'👋', count:'8 คำ', progress:75, tone:'yellow' }, { name:'ครอบครัว', icon:'🏠', count:'12 คำ', progress:40, tone:'mint' },
  { name:'อาหาร', icon:'🍜', count:'10 คำ', progress:20, tone:'peach' }, { name:'สี', icon:'🎨', count:'9 คำ', progress:100, tone:'blue' }, { name:'ตัวเลข', icon:'🔢', count:'15 คำ', progress:0, tone:'lavender' }, { name:'ชีวิตประจำวัน', icon:'☀️', count:'14 คำ', progress:55, tone:'rose' }
];
const words = [{ word:'สวัสดี', meaning:'คำกล่าวทักทาย แสดงความเป็นมิตร', emoji:'👋' }, { word:'ขอบคุณ', meaning:'กล่าวเพื่อแสดงความซาบซึ้งใจ', emoji:'💛' }, { word:'ครอบครัว', meaning:'กลุ่มคนที่มีความสัมพันธ์ใกล้ชิดกัน', emoji:'🏠' }];

function Layout({ children }) { const [open,setOpen]=useState(false); const location=useLocation(); const nav=[['/','หน้าหลัก',HomeIcon],['/lessons','บทเรียน',BookOpen],['/dashboard','ความคืบหน้า',BarChart3],['/profile','โปรไฟล์',UserRound]]; return <div className="app-shell">
  <header className="topbar"><Link to="/" className="brand"><span className="brand-mark"><Hand size={22}/></span><span>มือไมตรี</span></Link><button className="menu-btn" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button><nav className={open?'nav open':'nav'}>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} onClick={()=>setOpen(false)} className={({isActive})=>isActive?'active':''}><Icon size={18}/>{label}</NavLink>)}</nav><div className="avatar">น</div></header>
  <main>{children}</main><footer><span>มือไมตรี © 2024</span><span>เรียนรู้ด้วยสายตา เข้าใจกันด้วยหัวใจ</span></footer></div> }
function PageTitle({ eyebrow, title, description }) { return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1>{description&&<p>{description}</p>}</div></div> }
function Progress({ value }) { return <div className="progress"><span style={{width:`${value}%`}}/></div> }
function Button({ children, to, onClick, secondary=false, className='' }) { const C=to?Link:'button'; return <C to={to} onClick={onClick} className={`btn ${secondary?'btn-secondary':''} ${className}`}>{children}</C> }
function Home(){return <div className="container home"><section className="hero"><div className="hero-copy"><span className="eyebrow">พื้นที่เรียนรู้ที่ทุกคนเข้าถึงได้</span><h1>สื่อสารได้มากกว่า<br/><span>แค่ใช้เสียง</span></h1><p>เรียนรู้ภาษามือและภาษาไทยพื้นฐานทีละขั้น ผ่านภาพที่เข้าใจง่าย ออกแบบมาให้เรียนได้ด้วยตัวเอง</p><div className="hero-actions"><Button to="/lessons"><Play size={18} fill="currentColor"/> เริ่มเรียนภาษามือ</Button><Button to="/thai" secondary><PenLine size={18}/> เรียนภาษาไทยจากภาษามือ</Button></div><div className="trust"><span className="mini-avatars">น ก ม</span><span>มีผู้เรียนกว่า 1,200 คนกำลังฝึกไปด้วยกัน</span></div></div><div className="hero-art"><div className="sun"></div><div className="art-card"><span className="art-emoji">👋</span><span className="bubble">สวัสดี!</span><small>ท่าพื้นฐานคำทักทาย</small></div><div className="doodle one">✦</div><div className="doodle two">✦</div></div></section><section className="section"><div className="section-head"><div><span className="eyebrow">เลือกเส้นทางของคุณ</span><h2>วันนี้อยากเรียนอะไร?</h2></div><Link to="/lessons" className="text-link">ดูทั้งหมด <ChevronRight size={16}/></Link></div><div className="mode-grid"><Link to="/lessons" className="mode-card blue"><span className="mode-icon">🤟</span><div><h3>เรียนภาษามือ</h3><p>ฝึกคำศัพท์และท่าทาง<br/>ผ่านบทเรียนทีละขั้น</p></div><ChevronRight/></Link><Link to="/thai" className="mode-card orange"><span className="mode-icon">✍️</span><div><h3>ภาษาไทยจากภาษามือ</h3><p>เชื่อมโยงท่ามือสู่คำศัพท์<br/>และตัวอักษรไทย</p></div><ChevronRight/></Link></div></section><section className="continue-card"><div><span className="eyebrow">เรียนต่อจากครั้งที่แล้ว</span><h2>คำทักทายเบื้องต้น</h2><p>บทที่ 3 จาก 8 · เรียนไปแล้ว 75%</p><Progress value={75}/></div><Button to="/word/hello">เรียนต่อ <ChevronRight size={17}/></Button></section></div>}
function Lessons({ thai=false }){return <div className="container"><PageTitle eyebrow={thai?'เส้นทางที่ 2':'เส้นทางที่ 1'} title={thai?'ภาษาไทยจากภาษามือ':'เลือกบทเรียนของคุณ'} description={thai?'ฝึกเชื่อมโยงท่าภาษามือกับคำศัพท์ภาษาไทย':'เริ่มจากคำง่าย ๆ ในชีวิตประจำวัน แล้วค่อย ๆ สร้างคลังคำศัพท์ของคุณ'}/><div className="filter-row"><button className="filter active">ทั้งหมด</button><button className="filter">ยังไม่เริ่ม</button><button className="filter">กำลังเรียน</button><button className="filter">เรียนจบแล้ว</button></div><div className="category-grid">{cats.map((cat,i)=><Link to={thai?'/thai/card':'/category/'+i} className={`category-card ${cat.tone}`} key={cat.name}><div className="category-top"><span className="category-icon">{cat.icon}</span><span className={`status ${cat.progress===100?'done':cat.progress?'ongoing':'new'}`}>{cat.progress===100?'จบแล้ว':cat.progress?'กำลังเรียน':'ยังไม่เริ่ม'}</span></div><h3>{cat.name}</h3><p>{cat.count}</p><Progress value={cat.progress}/><div className="category-bottom"><span>{cat.progress}% สำเร็จ</span><ChevronRight size={18}/></div></Link>)}</div></div>}
function Placeholder({ type='image', label }){return <div className={`placeholder ${type}`}><div className="placeholder-icon">{type==='video'?<Video/>:<ImageIcon/>}</div><strong>{label||`พื้นที่ใส่${type==='video'?'วิดีโอ':'รูปภาพ'}`}</strong><span>Placeholder สำหรับสื่อการเรียนรู้</span>{type==='video'&&<div className="player"><button><Play size={17} fill="currentColor"/></button><span></span><small>0:00 / 0:30</small></div>}</div>}
function Stepper({ current=1, thai=false }){const steps=thai?['ดูวิดีโอ','ดูภาพ','ท่าภาษามือ','ตัวอักษรไทย']:['ความหมาย','ดูวิดีโอ','ฝึกทำท่า','ผลลัพธ์'];return <div className="stepper">{steps.map((s,i)=><React.Fragment key={s}><div className={`step ${i+1===current?'current':''} ${i+1<current?'passed':''}`}><span>{i+1<current?<Check size={15}/>:i+1}</span><small>{s}</small></div>{i<steps.length-1&&<i className={i+1<current?'line passed':''}/>}</React.Fragment>)}</div>}
function WordDetail({thai=false}){const nav=useNavigate();return <div className="container lesson-page"><Link to={thai?'/thai':'/lessons'} className="back"><ArrowLeft size={17}/> กลับไปหน้าบทเรียน</Link><Stepper current={1} thai={thai}/><div className="word-layout"><div><Placeholder label="ตำแหน่งใส่รูปภาพท่ามือ"/><div className="word-note"><CircleHelp size={18}/><span>ภาพประกอบจะช่วยให้คุณจดจำท่าได้ง่ายขึ้น</span></div></div><div className="word-copy"><span className="eyebrow">คำศัพท์บทที่ 3</span><h1>{thai?'ขอบคุณ':'สวัสดี'}</h1><p className="phonetic">{thai?'ขอบ-คุณ':'สะ-หวัด-ดี'}</p><div className="meaning"><span>ความหมาย</span><p>{thai?'คำที่ใช้กล่าวเพื่อแสดงความซาบซึ้งใจ':'คำกล่าวทักทาย แสดงความเป็นมิตรและความปรารถนาดี'}</p></div><Button onClick={()=>nav(thai?'/thai/video':'/video')} className="wide">ไปดูวิธีทำท่า <ChevronRight size={18}/></Button></div></div></div>}
function VideoDemo({thai=false}){return <div className="container lesson-page"><Link to={thai?'/thai/card':'/word/hello'} className="back"><ArrowLeft size={17}/> ย้อนกลับ</Link><Stepper current={2} thai={thai}/><div className="center-title"><span className="eyebrow">ขั้นตอนที่ 2</span><h1>ดูวิดีโอสาธิตท่าทาง</h1><p>สังเกตการเคลื่อนไหว แล้วลองทำตามอย่างช้า ๆ</p></div><div className="video-wrap"><Placeholder type="video" label="พื้นที่ใส่วิดีโอสาธิต"/></div><div className="practice-cta"><div><strong>พร้อมลองทำหรือยัง?</strong><span>เมื่อพร้อมแล้ว ไปฝึกทำท่าผ่านกล้องกันเลย</span></div><Button to={thai?'/thai/writing':'/practice'}><Camera size={18}/> เริ่มฝึกทำท่า</Button></div></div>}
function CameraPractice({thai=false}){const [status,setStatus]=useState('idle');return <div className="container lesson-page"><Link to={thai?'/thai/video':'/video'} className="back"><ArrowLeft size={17}/> ย้อนกลับ</Link><Stepper current={3} thai={thai}/><div className="center-title"><span className="eyebrow">ขั้นตอนที่ 3</span><h1>{thai?'ฝึกเขียนคำศัพท์':'ลองทำท่าตาม'}</h1><p>{thai?'ใช้นิ้ววาดตัวอักษรบนพื้นที่ด้านล่าง':'จัดมือให้อยู่ในกรอบ แล้วกดตรวจสอบเมื่อพร้อม'}</p></div><div className={`camera-box ${thai?'writing':''}`}>{thai?<><PenLine size={40}/><strong>พื้นที่ฝึกเขียน / Touch Input</strong><span>ระบบตรวจลายมือจะเชื่อมต่อในภายหลัง</span></>:<><Camera size={42}/><strong>พื้นที่เชื่อมต่อกล้อง</strong><span>Camera / AI จะเชื่อมต่อในภายหลัง</span></>}</div><div className="mock-status"><span className={`status-dot ${status}`}></span>{status==='checking'?'กำลังตรวจสอบ...':status==='correct'?'ทำได้ดีมาก!':'พร้อมตรวจสอบคำตอบของคุณ'}</div><div className="practice-actions"><Button secondary onClick={()=>setStatus('idle')}><RotateCcw size={17}/> เริ่มใหม่</Button><Button onClick={()=>{setStatus('checking');setTimeout(()=>setStatus('correct'),700)}}>{status==='checking'?'กำลังตรวจสอบ':'ตรวจสอบ'} <Check size={17}/></Button></div></div>}
function Feedback(){return <div className="container lesson-page"><Stepper current={4}/><div className="feedback-card"><div className="feedback-icon">✓</div><span className="eyebrow">ผลการฝึกของคุณ</span><h1>ทำได้ดีมาก!</h1><p>คุณทำท่า “สวัสดี” ได้ถูกต้อง<br/>ฝึกต่ออีกนิด แล้วจะคล่องขึ้นแน่นอน</p><div className="score"><strong>85</strong><span>/ 100 คะแนน</span></div><div className="feedback-actions"><Button to="/practice" secondary><RotateCcw size={17}/> ลองอีกครั้ง</Button><Button to="/lessons">ไปคำถัดไป <ChevronRight size={17}/></Button></div></div></div>}
function Dashboard(){return <div className="container"><PageTitle eyebrow="ภาพรวมการเรียนรู้" title="ความคืบหน้าของคุณ" description="ทุกก้าวเล็ก ๆ คือความสำเร็จ มาดูกันว่าคุณไปถึงไหนแล้ว"/><div className="stats"><div><span className="stat-icon yellow">🔥</span><strong>3</strong><small>วันที่เรียนต่อเนื่อง</small></div><div><span className="stat-icon blue">✓</span><strong>24</strong><small>คำศัพท์ที่เรียนแล้ว</small></div><div><span className="stat-icon mint">⏱</span><strong>2.5</strong><small>ชั่วโมงเรียนทั้งหมด</small></div></div><div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>ความคืบหน้าแต่ละหมวด</h2><span>อัปเดตวันนี้</span></div>{cats.slice(0,5).map(c=><div className="dash-row" key={c.name}><span>{c.icon} {c.name}</span><Progress value={c.progress}/><b>{c.progress}%</b></div>)}</section><section className="panel next"><div className="panel-head"><h2>บทเรียนถัดไป</h2></div><div className="next-art">🤟</div><span className="eyebrow">แนะนำสำหรับคุณ</span><h3>ประโยคใช้บ่อยในชีวิตประจำวัน</h3><p>เรียนรู้ 5 ประโยคใหม่ ใช้สื่อสารได้ทันที</p><Button to="/lessons" className="wide">เริ่มบทเรียน <ChevronRight size={17}/></Button></section></div></div>}
function Profile(){return <div className="container profile"><PageTitle eyebrow="พื้นที่ของฉัน" title="โปรไฟล์ผู้เรียน"/><div className="profile-card"><div className="profile-avatar">น</div><div><h2>น้องน้ำ</h2><p>สมาชิกตั้งแต่ มกราคม 2024</p></div><Button secondary>แก้ไขโปรไฟล์</Button></div><div className="panel preferences"><h2>เป้าหมายการเรียน</h2><div className="goal"><span>เรียนให้ได้ 10 นาทีต่อวัน</span><strong>7 / 10 นาที</strong></div><Progress value={70}/><div className="setting"><span>🔔 การแจ้งเตือนการเรียน</span><div className="toggle on"></div></div><div className="setting"><span>🌈 โหมดสีสบายตา</span><div className="toggle"></div></div></div></div>}
function App(){return <Layout><Routes><Route path="/" element={<Home/>}/><Route path="/lessons" element={<Lessons/>}/><Route path="/category/:id" element={<Lessons/>}/><Route path="/word/hello" element={<WordDetail/>}/><Route path="/video" element={<VideoDemo/>}/><Route path="/practice" element={<CameraPractice/>}/><Route path="/result" element={<Feedback/>}/><Route path="/thai" element={<Lessons thai/>}/><Route path="/thai/card" element={<WordDetail thai/>}/><Route path="/thai/video" element={<VideoDemo thai/>}/><Route path="/thai/writing" element={<CameraPractice thai/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/profile" element={<Profile/>}/><Route path="*" element={<Home/>}/></Routes></Layout>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
